name: Deploy MyST Site

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true # Gjøre fremtidige bygg raskere

      - name: Install dependencies
        run: uv sync # Dette lager det virtuelle miljøet automatisk fra pyproject.toml

      - name: Build site
        run: uvx --from jupyter-book jupyter-book build .

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_build/html'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4