name: Deploy Matematikk

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Build Site
        run: |
          BASE_URL=/Matematikk/ uvx jupyter-book build --html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_build/site' # MyST legger alt her automatisk

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4